# Blog redirects
# One per-year to scope this to old blog links only (otherwise we also match the new blog links!)
[[redirects]]
  from = "/2019/:month/:day/:slug"
  to = "/blog/2019/:month/:slug"

[[redirects]]
  from = "/2018/:month/:day/:slug"
  to = "/blog/2018/:month/:slug"

[[redirects]]
  from = "/2017/:month/:day/:slug"
  to = "/blog/2017/:month/:slug"

[[redirects]]
  from = "/2016/:month/:day/:slug"
  to = "/blog/2016/:month/:slug"

# Link post redirects
# 1 per-post
[[redirects]]
  from = "/links/2019/20191108/"
  to = "/blog/2019/11/interesting-links-november-2019/"

[[redirects]]
  from = "/links/2019/20191201/"
  to = "/blog/2019/12/interesting-links-december-2019/"

[[redirects]]
  from = "/links/2019/20191219/"
  to = "/blog/2019/12/more-interesting-links-december-2019/"

[[redirects]]
  from = "/links/2020/20200207/"
  to = "/blog/2020/02/interesting-links-february-2020/"

# There is no more archive page (/blog shows every post)
[[redirects]]
  from = "/blog/archive"
  to = "/blog"

[build]
  publish = "_site"
